#ifndef DELTA_PATCHER_H
#define DELTA_PATCHER_H

#include <stdint.h>

#include "boot_metadata.h"

#define DELTA_PATCHER_ERROR_BASE 0x000D0000UL

typedef enum
{
    DELTA_PATCHER_OK = 0,
    DELTA_PATCHER_NOT_DELTA,
    DELTA_PATCHER_SOURCE_REJECTED,
    DELTA_PATCHER_EXTERNAL_FLASH_INIT_FAILED,
    DELTA_PATCHER_HEADER_READ_FAILED,
    DELTA_PATCHER_HEADER_INVALID,
    DELTA_PATCHER_METADATA_MISMATCH,
    DELTA_PATCHER_PATCH_READ_FAILED,
    DELTA_PATCHER_PATCH_CRC_MISMATCH,
    DELTA_PATCHER_BASE_VERSION_MISMATCH,
    DELTA_PATCHER_BASE_CRC_MISMATCH,
    DELTA_PATCHER_METADATA_COMMIT_FAILED,
    DELTA_PATCHER_TARGET_ERASE_FAILED,
    DELTA_PATCHER_APPLY_FAILED,
    DELTA_PATCHER_TARGET_READ_FAILED,
    DELTA_PATCHER_TARGET_CRC_MISMATCH,
    DELTA_PATCHER_TARGET_VECTOR_INVALID
} DeltaPatcherStatus_t;

uint8_t DeltaPatcher_IsDeltaArtifact(void);

DeltaPatcherStatus_t DeltaPatcher_Process(
    const BootMetadata_t *metadata,
    BootMetadata_t *result_metadata);

#endif
