#ifndef FIRMWARE_VERSION_H
#define FIRMWARE_VERSION_H

#ifndef BOOTLOADER_VERSION
#define BOOTLOADER_VERSION 0x00000001UL
#endif

#ifndef APPLICATION_VERSION
#define APPLICATION_VERSION 0x00000001UL
#endif

#endif
