#ifndef OTA_STATUS_H
#define OTA_STATUS_H

typedef enum
{
    OTA_STATUS_OK = 0x00,
    OTA_STATUS_INVALID_PACKET = 0x01,
    OTA_STATUS_INVALID_STATE = 0x02,
    OTA_STATUS_WRONG_SEQUENCE = 0x03,
    OTA_STATUS_WRONG_OFFSET = 0x04,
    OTA_STATUS_PACKET_CRC_ERROR = 0x05,
    OTA_STATUS_STORAGE_ERROR = 0x06,
    OTA_STATUS_IMAGE_TOO_LARGE = 0x07,
    OTA_STATUS_UPDATE_ID_MISMATCH = 0x08,
    OTA_STATUS_BASE_MISMATCH = 0x09,
    OTA_STATUS_CONTAINER_ERROR = 0x0A,
    OTA_STATUS_SIGNATURE_ERROR = 0x0B,
    OTA_STATUS_VERSION_REJECTED = 0x0C,
    OTA_STATUS_BUSY = 0x0D,
    OTA_STATUS_RETRY_LATER = 0x0E,
    OTA_STATUS_INTERNAL_ERROR = 0x0F
} OtaStatus_t;

#endif
